### ISSUE TITLE
Demo not compiling.

### ISSUE THREAD

**Issue by alidaf** [winneymj/ESP8266_SSD1322#1]
Arduino: 1.6.8 (Linux), Board: "Arduino Pro or Pro Mini, ATmega328 (5V, 16 MHz)"

/home/alidaf/Arduino/libraries/ESP8266_SSD1322-master/ESP8266_SSD1322.cpp: In member function 'void ESP8266_SSD1322::ssd1322_dataBytes(uint8_t_, uint32_t)':
/home/alidaf/Arduino/libraries/ESP8266_SSD1322-master/ESP8266_SSD1322.cpp:365:7: error: 'class SPIClass' has no member named 'writeBytes'
   SPI.writeBytes(buf, size);
       ^
/home/alidaf/Arduino/libraries/ESP8266_SSD1322-master/ESP8266_SSD1322.cpp: In member function 'int ESP8266_SSD1322::drawUnicode(unsigned int, int, int, int)':
/home/alidaf/Arduino/libraries/ESP8266_SSD1322-master/ESP8266_SSD1322.cpp:1123:4: error: 'int8' was not declared in this scope
    int8 gap = 0;
    ^
/home/alidaf/Arduino/libraries/ESP8266_SSD1322-master/ESP8266_SSD1322.cpp:1123:9: error: expected ';' before 'gap'
    int8 gap = 0;
         ^
/home/alidaf/Arduino/libraries/ESP8266_SSD1322-master/ESP8266_SSD1322.cpp:1138:6: error: 'gap' was not declared in this scope
      gap = 1;
      ^
/home/alidaf/Arduino/libraries/ESP8266_SSD1322-master/ESP8266_SSD1322.cpp:1198:31: error: 'gap' was not declared in this scope
    drawFastHLine(x, pY, width+gap, textbgcolor);
                               ^
/home/alidaf/Arduino/libraries/ESP8266_SSD1322-master/ESP8266_SSD1322.cpp:1202:27: error: 'gap' was not declared in this scope
    fillRect(x, pY, (width+gap)_textsize, textsize, textbgcolor);
                           ^
/home/alidaf/Arduino/libraries/ESP8266_SSD1322-master/ESP8266_SSD1322.cpp:1239:16: error: 'gap' was not declared in this scope
  return (width+gap)*textsize;        // x +
                ^
exit status 1
Error compiling for board Arduino Pro or Pro Mini.

Any ideas

**Comment by winneymj** [comment]
Look like perhaps the Arduino SPI does not have SPI.writeBytes(buf, size); method.  I only tested/ran this on the ESP8266.
The issue with the 'gap' variable seems to be the declaration of int8 is not know.  I suggest you change this to int8_t and give that a try.  If you fix that it should get you down to the one problem with the SPI.  I suggest you take a look at the Arduino SPI class/header in the Arduino library directory to see if there is an equivalent.

**Comment by alidaf** [comment]
Ok. I'll try that but I think I'll have to write my own driver since your font format is different to the Adafruit one.
